services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample-db
    ports:
      - 5432:5432
    volumes:
      - ./dockers/postgresql/data:/var/lib/postgresql/data
    networks:
      - workspace

networks:
  workspace:
